[package]
name = "maybe-uring"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/hapsoc/hring"
documentation = "https://docs.rs/hring-buffet"
readme = "README.md"
description = """
Replicates some tokio-uring types to allow building code without it
"""

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["tokio-uring"]

[dependencies]
tokio = { version = "1.25.0", features = ["rt"] }

[target.'cfg(target_os = "linux")'.dependencies]
tokio-uring = { version = "0.4.0", optional = true }
