name: report-hpack

on:
  workflow_run:
    workflows: [test]
    types: [completed]
    
permissions:
  checks: write

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Download h2spec Report
        uses: dawidd6/action-download-artifact@v2
        with:
          name: h2spec-results
          workflow: ${{ github.event.workflow.id }}
          run_id: ${{ github.event.workflow_run.id }}
      - name: Stub Git repo for test-reporter
        run: |
          git init
      - name: Publish h2spec-hpack report
        uses: dorny/test-reporter@v1
        with:
          name: h2spec-hpack
          path: h2spec-hpack.xml
          reporter: java-junit