name: report

on:
  workflow_run:
    workflows: [test]
    types: [completed]
    
permissions:
  checks: write

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Download h2spec Report
        uses: dawidd6/action-download-artifact@v2
        with:
          name: h2spec-results
          workflow: ${{ github.event.workflow.id }}
          run_id: ${{ github.event.workflow_run.id }}
      - name: Publish h2spec Report
        uses: dorny/test-reporter@v1
        with:
          name: H2Spec Results
          path: h2spec-junit.xml
          reporter: java-junit