name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    env:
      RUSTC_WRAPPER: sccache
      CARGO_INCREMENTAL: 0
      CARGO_HOME: /vol/cargo
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Run tests
        run: |
          cd ${{ github.workspace }}
          sccache --zero-stats
          cargo clippy
          just ci-test
          mkdir tools
          export PATH=$PATH:${PWD}/tools
          (pushd && curl https://github.com/summerwind/h2spec/releases/download/v2.6.0/h2spec_linux_amd64.tar.gz | tar -xz && popd)
          just h2spec -j 'target/junit.xml'
          sccache --show-stats
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always() # always run even if the previous step fails
        with:
          report_paths: 'target/junit.xml'