name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    env:
      RUSTC_WRAPPER: sccache
      CARGO_INCREMENTAL: 0
      CARGO_HOME: /vol/cargo
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Run unit tests and h2spec
        run: |
          cd ${{ github.workspace }}
          sccache --zero-stats
          cargo clippy
          mkdir tools
          export PATH=$PATH:${PWD}/tools
          (pushd tools && curl https://github.com/summerwind/h2spec/releases/download/v2.6.0/h2spec_linux_amd64.tar.gz | tar -xz && popd)
          just ci-test
          sccache --show-stats
      - name: Upload h2spec Report
        uses: actions/upload-artifact@v3
        if: always() # always run even if the previous step fails
        with:
          name: h2spec-results
          path: 'target/h2spec-junit.xml'
          retention-days: 30
