name: test

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

jobs:
  test-macos:
    runs-on: macos-12
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Install Rust specified toolchain
        run: rustup show
      - name: Set up Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Install cargo-nextest
        run: |
          curl -LsSf https://get.nexte.st/latest/mac | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin
      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all-targets
      - name: Run cargo nextest
        uses: actions-rs/cargo@v1
        with:
          command: nextest
          args: run --profile ci
  test-windows:
    runs-on: windows-2022
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Install Rust specified toolchain
        run: rustup show
      - name: Set up Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Install cargo-nextest
        run: |
          $tmp = New-TemporaryFile | Rename-Item -NewName { $_ -replace 'tmp$', 'zip' } -PassThru
          Invoke-WebRequest -OutFile $tmp https://get.nexte.st/latest/windows
          $outputDir = if ($Env:CARGO_HOME) { Join-Path $Env:CARGO_HOME "bin" } else { "~/.cargo/bin" }
          $tmp | Expand-Archive -DestinationPath $outputDir -Force
          $tmp | Remove-Item
      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all-targets
      - name: Run cargo nextest
        uses: actions-rs/cargo@v1
        with:
          command: nextest
          args: run --profile ci
  test-linux:
    env:
      RUSTC_WRAPPER: sccache
      CARGO_INCREMENTAL: 0
      CARGO_HOME: /vol/cargo
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Run unit tests and h2spec
        run: |
          cd ${{ github.workspace }}
          sccache --zero-stats
          cargo clippy
          mkdir tools
          export PATH=$PATH:${PWD}/tools
          # (pushd tools && curl -L https://github.com/summerwind/h2spec/releases/download/v2.6.0/h2spec_linux_amd64.tar.gz | tar -xz && popd)
          # Uses https://github.com/summerwind/h2spec/pull/123, more precisely
          # https://github.com/fasterthanlime/h2spec/commit/72a6b9b2b01133d292bd74e019fde86c3638094a
          (pushd tools && curl -L http://misc.fasterthanli.me.s3.amazonaws.com/h2spec -o h2spec && chmod +x h2spec && popd)
          just ci-test
          sccache --show-stats
      - name: Upload h2spec Report
        uses: actions/upload-artifact@v3
        if: always() # always run even if the previous step fails
        with:
          name: h2spec-results
          path: |
            target/h2spec-generic.xml
            target/h2spec-hpack.xml
            target/h2spec-http2.xml
          retention-days: 280
